// <auto-generated />
using VasilevV.E._KT_31_21.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace VasilevV.E._KT_31_21.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    [Migration("20241025134054_CreateDb")]
    partial class CreateDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VasilevV.E._KT_31_21.Models.Discipline", b =>
                {
                    b.Property<int>("DisciplineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("discipline_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DisciplineId"));

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("c_discipline_direction");

                    b.Property<string>("DisciplineName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("c_discipline_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("с_discipline_isdeleted");

                    b.HasKey("DisciplineId")
                        .HasName("pk_cd_discipline_discipline_id");

                    b.HasIndex("Direction")
                        .HasDatabaseName("idx_cd_discipline_direction");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("idx_cd_discipline_isdeleted");

                    b.ToTable("cd_discipline", (string)null);
                });

            modelBuilder.Entity("VasilevV.E._KT_31_21.Models.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<int>("GroupCourse")
                        .HasColumnType("int")
                        .HasColumnName("с_group_groupcourse");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("c_group_groupname");

                    b.HasKey("GroupId")
                        .HasName("pk_cd_group_group_id");

                    b.ToTable("cd_group", (string)null);
                });

            modelBuilder.Entity("VasilevV.E._KT_31_21.Models.GroupDiscipline", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("int")
                        .HasColumnName("discipline_id");

                    b.HasKey("GroupId", "DisciplineId")
                        .HasName("pk_cd_group_discipline_group_discipline_id");

                    b.HasIndex("DisciplineId");

                    b.ToTable("cd_group_discipline", (string)null);
                });

            modelBuilder.Entity("VasilevV.E._KT_31_21.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("c_student_firstname");

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("c_student_group_id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("c_student_lastname");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("c_student_middlename");

                    b.HasKey("StudentId")
                        .HasName("pk_cd_student_student_id");

                    b.HasIndex("GroupId");

                    b.ToTable("cd_student", (string)null);
                });

            modelBuilder.Entity("VasilevV.E._KT_31_21.Models.GroupDiscipline", b =>
                {
                    b.HasOne("VasilevV.E._KT_31_21.Models.Discipline", "Discipline")
                        .WithMany()
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VasilevV.E._KT_31_21.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("VasilevV.E._KT_31_21.Models.Student", b =>
                {
                    b.HasOne("VasilevV.E._KT_31_21.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_f_group_id");

                    b.Navigation("Group");
                });
#pragma warning restore 612, 618
        }
    }
}
